function v210_close(fd)
% V210_CLOSE Closes a v210 video file.
%   V210_OPEN(fd) Close the video file described by fd.
%
%   The fd must be a descriptor returned by V210_CREATE or V210_OPEN. That is,
%   this function must be used to close all v210 video files, both opened for
%   reading and writing. If the file is opened for writing, the temporary raw
%   video file that was generated by V210_CREATE and used by V210_PUTFRAME to
%   store the video frames, is now encoded into the final container format with
%   the filename that was passed to V210_CREATE. For both reading and writing, the
%   temporary raw video file is removed from the disk. Closing a video file that
%   was opened for writing, can take time because of the encoding. A message is
%   printed when the encoding starts and ends.
%
%   The global FFPROBE and FFMPEG workspace variables must be set to the full path
%   of the ffprobe and ffmpeg programs, respectively.  

    global FFMPEG
 
    fclose(fd.fd);
    if fd.mode == 1
        disp( [ 'Saving ' fd.filename '...' ] ); 
        [st, out] = system([ FFMPEG ...
            ' -s ' num2str(fd.width) 'x' num2str(fd.height) ...
            ' -pix_fmt yuv422p16le -f rawvideo' ...
            ' -framerate ' num2str(fd.fps) ...
            ' -i ' fd.yuvname ...
            ' -f mov -vcodec v210' ...
            ' -framerate ' num2str(fd.fps) ...
            ' -y ' fd.filename ]);
        disp( [ 'Saving ' fd.filename ' done.' ] ); 
    end
    delete(fd.yuvname);
end
