function wmark = wmark_put_for_frame(w, wsize, f, v)
% WMARK_PUT_FOR_FRAME Adds an extracted watermark vector to accumulator v.
%   wmark = WMARK_PUT_FOR_FRAME(w, wsize, f, v) Adds watermark part w that
%   is extracted from frame number f, and has an expected size of wsize. It
%   returns the reconstructed original watermark image in wmark.
%
%   If the watermark data extracted from a frame of the video is not the full
%   representation of the original watermark image but only a part of it (i.e.
%   the method is not a simple frame-by-frame watermarking) then the original
%   watermark must be reconstructed from the extracted watermark parts. This 
%   function collects the watermark parts in a history. The watermark parts have
%   the same dimensions (width x height) as the original watermark. The original
%   watermark is reconstructed by summing the values from the last 5 frames in
%   the history. The history is continuously refreshed, i.e. when a new part comes
%   in, the oldest part is dropped. The function supports multiple history banks
%   (accumulators), bank #0 is used for left view, bank #1 is used for right view.
%   The parameter v selects the accumulator to use. Note that this function can
%   reconstruct the watermark from the parts generated by WMARK_GET_FOR_FRAME.

    persistent w_history
    max_history = 5;
    if f == 1
        w_history{v} = zeros( [ max_history wsize ]);
    end
    
    wmark = zeros(wsize);
    len = min(wsize(1)*wsize(2), size(w ,1));
    wmark(1:len) = -w(1:len);
    wmark = min(max(wmark, zeros(wsize)), ones(wsize));

    w_history{v}(2:max_history, :, :) = w_history{v}(1:max_history-1, :, :);
    w_history{v}(1,:,:) = wmark / max_history;
    
    wmark = squeeze(sum(w_history{v}, 1));
end
