function wmark_attack(a, infile, outfile)
   
    global FFMPEG
    tmpname = [tempname '.avi'];
    
    disp([ 'Encoding ' infile ' to h264 file: ' tmpname ]);
    [st, out] = system([ FFMPEG ...
        ' -i ' infile ...
        ' -y -c libx264 -pix_fmt yuv422p10le' ...
        ' -crf ' num2str(a*2) ...
        ' ' tmpname ]);
    disp('Encoding done');
    
    disp([ 'Decoding h264 file ' tmpname ' to ' outfile ]);
    [st, out] = system([ FFMPEG ...
        ' -i ' tmpname ...
        ' -y -c v210' ...
        ' ' outfile]);
    disp('Decoding done');
    
    delete(tmpname);
end